apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pci-app.fullname" . }}-secrets
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "pci-app.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-password: {{ .Values.database.auth.password | b64enc | quote }}
  db-url: {{ include "pci-app.dbUrl" . | b64enc | quote }}
